import type {
  Material,
  MaterialBundle,
  PortfolioProject,
  Assessment,
  Proposal,
  TrendData,
} from "./provider-types";

export const MOCK_MATERIALS: Material[] = [
  {
    id: "mat-1",
    providerId: "usr_provider_1",
    name: "Estate Emulsion - Matte",
    brand: "Farrow & Ball",
    category: "paint",
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&h=400&fit=crop",
    specs: { finish: "Matte", coverage: "60 sqft/L", voc: "Low VOC", dryTime: "4 hours" },
    pricePerUnit: 115,
    unit: "gallon",
    isFavorite: true,
    tags: ["premium", "matte", "interior"],
  },
  {
    id: "mat-2",
    providerId: "usr_provider_1",
    name: "Emerald Interior",
    brand: "Sherwin-Williams",
    category: "paint",
    imageUrl: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&h=400&fit=crop",
    specs: { finish: "Satin", coverage: "400 sqft/gal", voc: "Zero VOC", dryTime: "2 hours" },
    pricePerUnit: 79,
    unit: "gallon",
    isFavorite: true,
    tags: ["professional", "durable", "interior"],
  },
  {
    id: "mat-3",
    providerId: "usr_provider_1",
    name: "Carrara Marble Hex Tile",
    brand: "Daltile",
    category: "tile",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=400&fit=crop",
    specs: { size: "2\" hex", material: "Marble", finish: "Honed", thickness: "10mm" },
    pricePerUnit: 18,
    unit: "sqft",
    isFavorite: false,
    tags: ["marble", "hex", "bathroom"],
  },
  {
    id: "mat-4",
    providerId: "usr_provider_1",
    name: "White Shaker Cabinet Door",
    brand: "KraftMaid",
    category: "cabinetry",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
    specs: { style: "Shaker", material: "Maple", finish: "Painted White", hinge: "Soft-close" },
    pricePerUnit: 145,
    unit: "door",
    isFavorite: true,
    tags: ["shaker", "white", "kitchen"],
  },
  {
    id: "mat-5",
    providerId: "usr_provider_1",
    name: "Quartz Countertop - Calacatta",
    brand: "Caesarstone",
    category: "countertop",
    imageUrl: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&h=400&fit=crop",
    specs: { thickness: "3cm", finish: "Polished", color: "Calacatta Nuvo", edge: "Eased" },
    pricePerUnit: 85,
    unit: "sqft",
    isFavorite: true,
    tags: ["quartz", "calacatta", "premium"],
  },
  {
    id: "mat-6",
    providerId: "usr_provider_1",
    name: "Brushed Brass Pull",
    brand: "Amerock",
    category: "hardware",
    imageUrl: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400&h=400&fit=crop",
    specs: { size: "5\" center-to-center", finish: "Brushed Gold", material: "Zinc Alloy" },
    pricePerUnit: 12,
    unit: "piece",
    isFavorite: false,
    tags: ["brass", "pull", "modern"],
  },
  {
    id: "mat-7",
    providerId: "usr_provider_1",
    name: "White Oak Engineered Hardwood",
    brand: "Shaw",
    category: "flooring",
    imageUrl: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=400&h=400&fit=crop",
    specs: { width: "7\"", thickness: "9/16\"", finish: "Wire-brushed", install: "Float or glue" },
    pricePerUnit: 8,
    unit: "sqft",
    isFavorite: true,
    tags: ["hardwood", "oak", "engineered"],
  },
  {
    id: "mat-8",
    providerId: "usr_provider_1",
    name: "Matte Black Rain Showerhead",
    brand: "Delta",
    category: "fixture",
    imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=400&fit=crop",
    specs: { size: "10\" round", finish: "Matte Black", flow: "1.75 GPM", mount: "Ceiling" },
    pricePerUnit: 289,
    unit: "piece",
    isFavorite: false,
    tags: ["matte black", "rain", "modern"],
  },
  {
    id: "mat-9",
    providerId: "usr_provider_1",
    name: "Pendant Globe Light",
    brand: "West Elm",
    category: "lighting",
    imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&h=400&fit=crop",
    specs: { diameter: "12\"", material: "Glass + Brass", bulb: "E26", cord: "Adjustable 6ft" },
    pricePerUnit: 199,
    unit: "piece",
    isFavorite: false,
    tags: ["pendant", "globe", "brass"],
  },
  {
    id: "mat-10",
    providerId: "usr_provider_1",
    name: "Subway Tile - Handmade",
    brand: "Fireclay Tile",
    category: "tile",
    imageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=400&h=400&fit=crop",
    specs: { size: "3x6", material: "Ceramic", finish: "Glossy", thickness: "8mm" },
    pricePerUnit: 15,
    unit: "sqft",
    isFavorite: true,
    tags: ["subway", "handmade", "backsplash"],
  },
];

export const MOCK_MATERIAL_BUNDLES: MaterialBundle[] = [
  {
    id: "bundle-1",
    providerId: "usr_provider_1",
    name: "Premium Kitchen Package",
    description: "Complete kitchen upgrade with shaker cabinets, quartz countertops, and brass hardware",
    materialIds: ["mat-4", "mat-5", "mat-6", "mat-10"],
    totalPrice: 260,
    category: "kitchen",
    createdAt: "2025-03-01T00:00:00Z",
  },
  {
    id: "bundle-2",
    providerId: "usr_provider_1",
    name: "Modern Bathroom Set",
    description: "Matte black fixtures, marble hex tile, and premium paint",
    materialIds: ["mat-3", "mat-8", "mat-1"],
    totalPrice: 422,
    category: "bathroom",
    createdAt: "2025-02-15T00:00:00Z",
  },
];

export const MOCK_PORTFOLIO: PortfolioProject[] = [
  {
    id: "port-1",
    providerId: "usr_provider_1",
    title: "Coastal Kitchen Transformation",
    description: "Complete kitchen renovation with custom shaker cabinets, quartz countertops, and a new subway tile backsplash. The client wanted a bright, airy feel inspired by their beach house.",
    beforeImageUrl: "https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=800&h=600&fit=crop",
    afterImageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop",
    category: "kitchen",
    style: "coastal",
    tags: ["cabinets", "countertops", "backsplash", "full-renovation"],
    materials: [
      { materialId: "mat-4", name: "White Shaker Cabinet Door", brand: "KraftMaid", quantity: 24, unit: "doors" },
      { materialId: "mat-5", name: "Quartz Countertop - Calacatta", brand: "Caesarstone", quantity: 45, unit: "sqft" },
      { materialId: "mat-10", name: "Subway Tile - Handmade", brand: "Fireclay Tile", quantity: 30, unit: "sqft" },
    ],
    scope: "Full kitchen renovation including cabinet replacement, countertop installation, backsplash tiling, and painting",
    budget: { min: 28000, max: 35000 },
    duration: "6 weeks",
    sqft: 220,
    isPublic: true,
    viewCount: 1247,
    saveCount: 89,
    createdAt: "2025-02-10T00:00:00Z",
  },
  {
    id: "port-2",
    providerId: "usr_provider_1",
    title: "Matte Black Master Bath",
    description: "Luxury bathroom renovation featuring matte black fixtures, marble hex floor tile, and Farrow & Ball wall finish. Transformed a dated 90s bathroom into a modern spa-like retreat.",
    beforeImageUrl: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&h=600&fit=crop",
    afterImageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop",
    category: "bathroom",
    style: "industrial",
    tags: ["matte-black", "marble", "luxury", "spa"],
    materials: [
      { materialId: "mat-3", name: "Carrara Marble Hex Tile", brand: "Daltile", quantity: 85, unit: "sqft" },
      { materialId: "mat-8", name: "Matte Black Rain Showerhead", brand: "Delta", quantity: 1, unit: "piece" },
      { materialId: "mat-1", name: "Estate Emulsion - Matte", brand: "Farrow & Ball", quantity: 3, unit: "gallons" },
    ],
    scope: "Complete bathroom gut renovation including plumbing reroute, tile installation, fixtures, and premium wall finish",
    budget: { min: 18000, max: 24000 },
    duration: "4 weeks",
    sqft: 120,
    isPublic: true,
    viewCount: 892,
    saveCount: 67,
    createdAt: "2025-01-20T00:00:00Z",
  },
  {
    id: "port-3",
    providerId: "usr_provider_1",
    title: "Scandinavian Living Room Refresh",
    description: "A full interior repaint with Sherwin-Williams Emerald in warm whites, complemented by new white oak engineered hardwood flooring. Minimal disruption, maximum impact.",
    beforeImageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
    afterImageUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&h=600&fit=crop",
    category: "living-room",
    style: "scandinavian",
    tags: ["painting", "flooring", "minimal", "warm-white"],
    materials: [
      { materialId: "mat-2", name: "Emerald Interior", brand: "Sherwin-Williams", quantity: 8, unit: "gallons" },
      { materialId: "mat-7", name: "White Oak Engineered Hardwood", brand: "Shaw", quantity: 350, unit: "sqft" },
    ],
    scope: "Interior painting (walls and trim) plus full flooring replacement",
    budget: { min: 8500, max: 12000 },
    duration: "2 weeks",
    sqft: 350,
    isPublic: true,
    viewCount: 2134,
    saveCount: 156,
    createdAt: "2025-03-05T00:00:00Z",
  },
  {
    id: "port-4",
    providerId: "usr_provider_1",
    title: "Modern Farmhouse Exterior",
    description: "Board and batten siding repaint with crisp white body and charcoal trim. Included power washing, scraping, priming, and two coats of premium exterior paint.",
    beforeImageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    afterImageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    category: "exterior",
    style: "farmhouse",
    tags: ["exterior", "siding", "trim", "power-wash"],
    materials: [
      { materialId: "mat-2", name: "Emerald Exterior", brand: "Sherwin-Williams", quantity: 25, unit: "gallons" },
    ],
    scope: "Full exterior repaint including power washing, surface prep, priming, and 2-coat application",
    budget: { min: 12000, max: 16000 },
    duration: "3 weeks",
    sqft: 2800,
    isPublic: true,
    viewCount: 1567,
    saveCount: 112,
    createdAt: "2024-12-15T00:00:00Z",
  },
];

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    id: "assess-1",
    providerId: "usr_provider_1",
    title: "Beverly Hills Master Suite",
    clientName: "Sarah Mitchell",
    address: "1240 Sunset Blvd, Beverly Hills, CA",
    roomType: "bedroom",
    estimatedSqft: 450,
    projectDescription: "Complete repaint of master bedroom suite with premium low-VOC finish. Client wants warm white tones with accent wall.",
    urgency: "normal",
    sitePhotos: [
      { id: "sp-1", url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop", category: "before", caption: "Main wall with cracking" },
      { id: "sp-2", url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop", category: "issue", caption: "Crown molding peeling" },
      { id: "sp-3", url: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&h=600&fit=crop", category: "detail", caption: "Water stain on ceiling" },
    ],
    fieldNotes: "Access through front door. Client has pets — need drop cloths. Crown molding needs extra attention. Water stain may indicate leak — recommend plumber check before paint.",
    visitDate: "2025-03-18",
    visitCompleted: true,
    imageUrls: [
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop",
    ],
    condition: "fair",
    conditionNotes: [
      "Walls show minor cracking and nail pops",
      "Crown molding has visible paint peeling",
      "Ceiling has water stain near window (check for leak)",
      "Baseboards in acceptable condition with light scuffing",
    ],
    scopeItems: [
      { id: "si-1", description: "Wall repair - patch cracks and nail pops", category: "preparation", estimatedCost: { min: 200, max: 350 }, materialQty: 1, materialUnit: "kit", isIncluded: true },
      { id: "si-2", description: "Ceiling repair - address water stain", category: "preparation", estimatedCost: { min: 150, max: 300 }, materialQty: 1, materialUnit: "kit", isIncluded: true },
      { id: "si-3", description: "Surface preparation & sanding", category: "preparation", estimatedCost: { min: 300, max: 450 }, materialQty: 1, materialUnit: "flat", isIncluded: true },
      { id: "si-4", description: "Premium low-VOC paint application (2 coats)", category: "labor", estimatedCost: { min: 800, max: 1200 }, materialQty: 3, materialUnit: "gallons", isIncluded: true },
      { id: "si-5", description: "Crown molding scrape & repaint", category: "finishing", estimatedCost: { min: 250, max: 400 }, materialQty: 1, materialUnit: "quart", isIncluded: true },
      { id: "si-6", description: "Baseboard touch-up", category: "finishing", estimatedCost: { min: 100, max: 200 }, materialQty: 1, materialUnit: "quart", isIncluded: false },
    ],
    totalEstimate: { min: 1700, max: 2700 },
    materialRecommendations: [
      { name: "Emerald Interior - Satin", brand: "Sherwin-Williams", quantity: 3, unit: "gallons", unitPrice: 79 },
      { name: "Pro-Grade Joint Compound", brand: "DAP", quantity: 1, unit: "quart", unitPrice: 12 },
      { name: "Premium Painter's Tape", brand: "FrogTape", quantity: 4, unit: "rolls", unitPrice: 8 },
    ],
    pricing: {
      lineItems: [
        { id: "pl-1", scopeItemId: "si-1", description: "Wall repair - patch cracks and nail pops", materialCost: 45, laborHours: 3, laborRate: 65, subtotal: 240 },
        { id: "pl-2", scopeItemId: "si-2", description: "Ceiling repair - address water stain", materialCost: 35, laborHours: 2, laborRate: 65, subtotal: 165 },
        { id: "pl-3", scopeItemId: "si-3", description: "Surface preparation & sanding", materialCost: 60, laborHours: 4, laborRate: 65, subtotal: 320 },
        { id: "pl-4", scopeItemId: "si-4", description: "Premium low-VOC paint application (2 coats)", materialCost: 237, laborHours: 8, laborRate: 65, subtotal: 757 },
        { id: "pl-5", scopeItemId: "si-5", description: "Crown molding scrape & repaint", materialCost: 25, laborHours: 3, laborRate: 65, subtotal: 220 },
      ],
      materialTotal: 402,
      laborTotal: 1300,
      subtotal: 1702,
      profitMargin: 20,
      discount: 0,
      taxRate: 8.25,
      taxAmount: 168.05,
      total: 2210.45,
    },
    status: "complete",
    createdAt: "2025-03-20T10:00:00Z",
    updatedAt: "2025-03-22T14:00:00Z",
  },
  {
    id: "assess-2",
    providerId: "usr_provider_1",
    title: "West Hollywood Kitchen Cabinets",
    clientName: "James Park",
    address: "8721 Santa Monica Blvd, West Hollywood, CA",
    roomType: "kitchen",
    estimatedSqft: 180,
    projectDescription: "Complete refinishing of 24 cabinet doors and 8 drawers. Client wants modern white satin finish.",
    urgency: "high",
    sitePhotos: [
      { id: "sp-4", url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop", category: "before", caption: "Current cabinet condition" },
    ],
    fieldNotes: "Cabinets are solid maple — good base for refinishing. Some hinge holes need filling. Kitchen will be out of use for 5 days.",
    visitDate: "2025-03-25",
    visitCompleted: true,
    imageUrls: [
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
    ],
    condition: "good",
    conditionNotes: [
      "Cabinet doors are structurally sound",
      "Original finish is yellowing — needs full strip and repaint",
      "Two hinge holes need wood filler",
    ],
    scopeItems: [
      { id: "si-7", description: "Remove all doors and drawer fronts", category: "preparation", estimatedCost: { min: 200, max: 300 }, materialQty: 32, materialUnit: "pieces", isIncluded: true },
      { id: "si-8", description: "Strip existing finish", category: "preparation", estimatedCost: { min: 400, max: 600 }, materialQty: 1, materialUnit: "lot", isIncluded: true },
      { id: "si-9", description: "Sand and prime all surfaces", category: "preparation", estimatedCost: { min: 350, max: 500 }, materialQty: 2, materialUnit: "gallons", isIncluded: true },
      { id: "si-10", description: "Professional spray application (2 coats)", category: "labor", estimatedCost: { min: 1500, max: 2000 }, materialQty: 4, materialUnit: "gallons", isIncluded: true },
      { id: "si-11", description: "New soft-close hinges", category: "materials", estimatedCost: { min: 400, max: 500 }, materialQty: 48, materialUnit: "pieces", isIncluded: true },
      { id: "si-12", description: "Reinstallation and adjustment", category: "finishing", estimatedCost: { min: 300, max: 400 }, materialQty: 32, materialUnit: "pieces", isIncluded: true },
    ],
    totalEstimate: { min: 3150, max: 4300 },
    materialRecommendations: [
      { name: "Cabinet Coat - Satin White", brand: "Benjamin Moore", quantity: 4, unit: "gallons", unitPrice: 65 },
      { name: "Soft-Close Concealed Hinge", brand: "Blum", quantity: 48, unit: "pieces", unitPrice: 8 },
      { name: "Bonding Primer", brand: "Zinsser", quantity: 2, unit: "gallons", unitPrice: 42 },
    ],
    pricing: null,
    status: "in_progress",
    createdAt: "2025-03-25T09:00:00Z",
    updatedAt: "2025-03-26T11:00:00Z",
  },
  {
    id: "assess-3",
    providerId: "usr_provider_1",
    title: "Malibu Exterior Renovation",
    clientName: "David Kim",
    address: "21450 Pacific Coast Hwy, Malibu, CA",
    roomType: "exterior",
    estimatedSqft: 2800,
    projectDescription: "Full exterior repaint of ocean-front residence. Salt air exposure requires specialized paint.",
    urgency: "low",
    sitePhotos: [],
    fieldNotes: "",
    visitDate: "",
    visitCompleted: false,
    imageUrls: [],
    condition: "fair",
    conditionNotes: [],
    scopeItems: [],
    totalEstimate: { min: 0, max: 0 },
    materialRecommendations: [],
    pricing: null,
    status: "draft",
    createdAt: "2025-04-01T08:00:00Z",
    updatedAt: "2025-04-01T08:00:00Z",
  },
];

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: "prop-1",
    providerId: "usr_provider_1",
    clientName: "Sarah Mitchell",
    projectTitle: "Master Bedroom Premium Repaint",
    template: "premium",
    blocks: [
      { id: "b1", type: "text", order: 0, data: { heading: "Project Overview", body: "A premium interior repaint of your master bedroom suite, featuring Sherwin-Williams Emerald in a warm white tone with meticulous surface preparation." } },
      { id: "b2", type: "before-after", order: 1, data: { beforeUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop", afterUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&h=600&fit=crop" } },
      { id: "b3", type: "materials", order: 2, data: { materialIds: ["mat-2"], quantities: [3] } },
      { id: "b4", type: "palette", order: 3, data: { colors: ["#F1EEE8", "#D5CFC3", "#8B8578"] } },
      { id: "b5", type: "timeline", order: 4, data: { phases: [{ name: "Prep & Protection", days: 1 }, { name: "Surface Repair", days: 1 }, { name: "Paint Application", days: 2 }, { name: "Final Inspection", days: 1 }] } },
      { id: "b6", type: "cost", order: 5, data: { subtotal: 1450, tax: 119.63, total: 1569.63 } },
    ],
    totalCost: 1569.63,
    status: "sent",
    sentAt: "2025-03-22T14:00:00Z",
    viewedAt: "2025-03-22T16:30:00Z",
    createdAt: "2025-03-21T10:00:00Z",
    updatedAt: "2025-03-22T14:00:00Z",
  },
  {
    id: "prop-2",
    providerId: "usr_provider_1",
    clientName: "James Park",
    projectTitle: "Kitchen Cabinet Refinishing",
    template: "detailed",
    blocks: [
      { id: "b7", type: "text", order: 0, data: { heading: "Scope of Work", body: "Complete refinishing of 24 cabinet doors and 8 drawer fronts with professional spray application." } },
      { id: "b8", type: "materials", order: 1, data: { materialIds: ["mat-4", "mat-6"], quantities: [24, 32] } },
      { id: "b9", type: "cost", order: 2, data: { subtotal: 3800, tax: 313.50, total: 4113.50 } },
    ],
    totalCost: 4113.50,
    status: "accepted",
    sentAt: "2025-03-15T09:00:00Z",
    viewedAt: "2025-03-15T11:00:00Z",
    createdAt: "2025-03-14T16:00:00Z",
    updatedAt: "2025-03-16T08:00:00Z",
  },
  {
    id: "prop-3",
    providerId: "usr_provider_1",
    clientName: "Lisa Chen",
    projectTitle: "Full Home Interior Repaint",
    template: "minimal",
    blocks: [
      { id: "b10", type: "text", order: 0, data: { heading: "Project Summary", body: "Complete interior repaint of all common areas including living room, dining room, hallways, and stairway." } },
      { id: "b11", type: "cost", order: 1, data: { subtotal: 8200, tax: 676.50, total: 8876.50 } },
    ],
    totalCost: 8876.50,
    status: "draft",
    createdAt: "2025-03-25T08:00:00Z",
    updatedAt: "2025-03-25T08:00:00Z",
  },
];

export const MOCK_TREND_DATA: TrendData = {
  styleTrends: [
    { style: "modern", searches: 4520, change: 12 },
    { style: "farmhouse", searches: 3890, change: -5 },
    { style: "coastal", searches: 3650, change: 18 },
    { style: "minimalist", searches: 3200, change: 24 },
    { style: "industrial", searches: 2870, change: 8 },
    { style: "scandinavian", searches: 2540, change: 15 },
    { style: "mid-century", searches: 2100, change: 6 },
    { style: "contemporary", searches: 1950, change: -2 },
    { style: "traditional", searches: 1800, change: -8 },
    { style: "bohemian", searches: 1650, change: 10 },
    { style: "art-deco", searches: 1200, change: 22 },
    { style: "rustic", searches: 980, change: -12 },
  ],
  popularColors: [
    { hex: "#F1EEE8", name: "Extra White", saves: 892 },
    { hex: "#D0C8B8", name: "Agreeable Gray", saves: 867 },
    { hex: "#F3EEDE", name: "White Dove", saves: 732 },
    { hex: "#3C4557", name: "Hale Navy", saves: 621 },
    { hex: "#2B2B2B", name: "Railings", saves: 543 },
    { hex: "#7B8A82", name: "Evergreen Fog", saves: 412 },
    { hex: "#4A6741", name: "Forest Moss", saves: 298 },
    { hex: "#D4956B", name: "Canyon Clay", saves: 256 },
  ],
  categoryDemand: [
    { category: "kitchen", label: "Kitchen", projects: 156, avgBudget: 32000, change: 14 },
    { category: "bathroom", label: "Bathroom", projects: 134, avgBudget: 18500, change: 8 },
    { category: "exterior", label: "Exterior", projects: 98, avgBudget: 14000, change: 22 },
    { category: "living-room", label: "Living Room", projects: 87, avgBudget: 8500, change: 5 },
    { category: "bedroom", label: "Bedroom", projects: 65, avgBudget: 4200, change: -3 },
    { category: "office", label: "Office", projects: 43, avgBudget: 3800, change: 32 },
    { category: "dining-room", label: "Dining Room", projects: 28, avgBudget: 5200, change: -6 },
    { category: "hallway", label: "Hallway", projects: 21, avgBudget: 2400, change: 1 },
  ],
  priceBenchmarks: [
    { category: "kitchen", label: "Kitchen Remodel", avgPrice: 32000, yourPrice: 31500, minPrice: 18000, maxPrice: 65000 },
    { category: "bathroom", label: "Bathroom Reno", avgPrice: 18500, yourPrice: 21000, minPrice: 8000, maxPrice: 45000 },
    { category: "exterior", label: "Exterior Paint", avgPrice: 14000, yourPrice: 14000, minPrice: 5000, maxPrice: 28000 },
    { category: "living-room", label: "Interior Paint", avgPrice: 8500, yourPrice: 10250, minPrice: 2500, maxPrice: 18000 },
    { category: "bedroom", label: "Room Repaint", avgPrice: 4200, yourPrice: 3800, minPrice: 1200, maxPrice: 8000 },
  ],
  seasonalHighlight: {
    season: "Spring 2026",
    topCategory: "Exterior",
    description: "Exterior projects surge 22% as homeowners prepare for summer. Curb appeal and deck restoration lead demand.",
  },
};
