import type { FeedItem, PaintColor, ColorPalette, Moodboard } from "./types";

export const FEED_ITEMS: FeedItem[] = [
  { id: "feed-1", type: "room", title: "Limewash Living Room", description: "Organic limewash walls with linen furnishings create an effortlessly elegant atmosphere", imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=1000&fit=crop", category: "living-room", style: "minimalist", tags: ["limewash", "organic", "neutral"], savedCount: 342 },
  { id: "feed-2", type: "color", title: "Sherwin-Williams Emerald", imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4ea0d?w=800&h=1100&fit=crop", category: "living-room", style: "contemporary", tags: ["green", "bold", "accent"], color: { hex: "#2E3B32", name: "Pewter Green", brand: "Sherwin-Williams" }, savedCount: 256 },
  { id: "feed-3", type: "room", title: "Venetian Plaster Hallway", description: "Polished Venetian plaster walls with warm lighting and minimalist decor", imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=600&fit=crop", category: "hallway", style: "contemporary", tags: ["venetian plaster", "warm", "texture"], savedCount: 189 },
  { id: "feed-4", type: "color", title: "Farrow & Ball School House White", imageUrl: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=1100&fit=crop", category: "bedroom", style: "traditional", tags: ["white", "classic", "clean"], color: { hex: "#F4EDE4", name: "School House White", brand: "Farrow & Ball" }, savedCount: 428 },
  { id: "feed-5", type: "room", title: "Wainscoting Details", description: "Classic wainscoting painted in matte finish with contrasting wall colors", imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7def511?w=800&h=1100&fit=crop", category: "dining-room", style: "traditional", tags: ["wainscoting", "trim", "detail"], savedCount: 167 },
  { id: "feed-6", type: "texture", title: "Textured Ceilings", description: "Modern textured ceiling treatment that adds depth and dimension", imageUrl: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&h=800&fit=crop", category: "living-room", style: "contemporary", tags: ["ceiling", "texture", "dimensional"], savedCount: 93 },
  { id: "feed-7", type: "room", title: "Coastal Kitchen Refresh", description: "Light blues and natural wood bring seaside serenity to this modern kitchen", imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=1000&fit=crop", category: "kitchen", style: "coastal", tags: ["blue", "wood", "airy"], savedCount: 514 },
  { id: "feed-8", type: "room", title: "Matte Black Bathroom", description: "Bold matte black fixtures against white subway tile for dramatic contrast", imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=1200&fit=crop", category: "bathroom", style: "industrial", tags: ["matte black", "contrast", "fixtures"], savedCount: 387 },
  { id: "feed-9", type: "color", title: "Benjamin Moore Hale Navy", imageUrl: "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&h=900&fit=crop", category: "office", style: "traditional", tags: ["navy", "deep", "statement"], color: { hex: "#3C4557", name: "Hale Navy", brand: "Benjamin Moore" }, savedCount: 621 },
  { id: "feed-10", type: "room", title: "Scandinavian Bedroom", description: "Warm whites and natural textures create a calming Scandi retreat", imageUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&h=800&fit=crop", category: "bedroom", style: "scandinavian", tags: ["white", "minimal", "cozy"], savedCount: 445 },
  { id: "feed-11", type: "finish", title: "Brushed Brass Hardware", description: "Warm brushed brass cabinet hardware elevates any kitchen design", imageUrl: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&h=700&fit=crop", category: "kitchen", style: "contemporary", tags: ["brass", "hardware", "warm"], savedCount: 278 },
  { id: "feed-12", type: "room", title: "Mid-Century Study", description: "Rich walnut, olive tones, and geometric patterns define this retro workspace", imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=1000&fit=crop", category: "office", style: "mid-century", tags: ["walnut", "retro", "olive"], savedCount: 198 },
  { id: "feed-13", type: "color", title: "Behr Blank Canvas", imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1000&fit=crop", category: "living-room", style: "minimalist", tags: ["warm white", "neutral", "versatile"], color: { hex: "#F0E7D8", name: "Blank Canvas", brand: "Behr" }, savedCount: 732 },
  { id: "feed-14", type: "room", title: "Industrial Loft Kitchen", description: "Exposed brick, concrete counters, and metal shelving", imageUrl: "https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=800&h=800&fit=crop", category: "kitchen", style: "industrial", tags: ["brick", "concrete", "metal"], savedCount: 321 },
  { id: "feed-15", type: "texture", title: "Lime-Washed Brick", description: "European-style lime-washed brick adds rustic character", imageUrl: "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop", category: "living-room", style: "farmhouse", tags: ["brick", "limewash", "rustic"], savedCount: 156 },
  { id: "feed-16", type: "room", title: "Art Deco Powder Room", description: "Geometric tiles, gold accents, and bold wallpaper make a statement", imageUrl: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&h=1200&fit=crop", category: "bathroom", style: "art-deco", tags: ["geometric", "gold", "wallpaper"], savedCount: 243 },
  { id: "feed-17", type: "room", title: "Bohemian Living Space", description: "Layered textiles, warm earth tones, and global-inspired decor", imageUrl: "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&h=900&fit=crop", category: "living-room", style: "bohemian", tags: ["textiles", "earthy", "layered"], savedCount: 367 },
  { id: "feed-18", type: "color", title: "SW Agreeable Gray", imageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=900&fit=crop", category: "living-room", style: "contemporary", tags: ["greige", "neutral", "bestseller"], color: { hex: "#D0C8B8", name: "Agreeable Gray", brand: "Sherwin-Williams" }, savedCount: 892 },
  { id: "feed-19", type: "room", title: "Farmhouse Exterior", description: "Classic board and batten siding with a modern edge", imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=800&fit=crop", category: "exterior", style: "farmhouse", tags: ["board-batten", "siding", "white"], savedCount: 534 },
  { id: "feed-20", type: "finish", title: "Satin Black Trim", description: "Satin black window and door trim for a sophisticated frame effect", imageUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=1000&fit=crop", category: "living-room", style: "modern", tags: ["black trim", "contrast", "satin"], savedCount: 211 },
  { id: "feed-21", type: "room", title: "Rustic Dining Room", description: "Reclaimed wood table, stone accent wall, and warm ambient lighting", imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&h=700&fit=crop", category: "dining-room", style: "rustic", tags: ["wood", "stone", "warm"], savedCount: 189 },
  { id: "feed-22", type: "room", title: "Modern Exterior Dark", description: "Charcoal exterior paint with clean lines and warm wood accents", imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=900&fit=crop", category: "exterior", style: "modern", tags: ["dark", "charcoal", "contemporary"], savedCount: 456 },
  { id: "feed-23", type: "color", title: "BM White Dove", imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=800&fit=crop", category: "kitchen", style: "traditional", tags: ["warm white", "classic", "timeless"], color: { hex: "#F3EEDE", name: "White Dove", brand: "Benjamin Moore" }, savedCount: 867 },
  { id: "feed-24", type: "room", title: "Minimalist Bedroom Suite", description: "Floating bed, recessed lighting, and barely-there color palette", imageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&h=1000&fit=crop", category: "bedroom", style: "minimalist", tags: ["floating", "recessed", "monochrome"], savedCount: 298 },
  { id: "feed-25", type: "texture", title: "Micro Cement Walls", description: "Seamless micro cement for a raw, industrial-luxe finish", imageUrl: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&h=700&fit=crop", category: "bathroom", style: "industrial", tags: ["micro cement", "seamless", "raw"], savedCount: 176 },
  { id: "feed-26", type: "room", title: "Coastal Dining Nook", description: "Pale wood, rattan, and ocean blues for relaxed seaside dining", imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4ea0d?w=800&h=900&fit=crop", category: "dining-room", style: "coastal", tags: ["rattan", "ocean", "pale wood"], savedCount: 234 },
  { id: "feed-27", type: "room", title: "Japandi Bathroom", description: "Japanese minimalism meets Scandinavian warmth with natural materials", imageUrl: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=1100&fit=crop", category: "bathroom", style: "minimalist", tags: ["japandi", "natural", "serene"], savedCount: 412 },
  { id: "feed-28", type: "color", title: "F&B Railings", imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1200&fit=crop", category: "exterior", style: "traditional", tags: ["almost-black", "dramatic", "classic"], color: { hex: "#2B2B2B", name: "Railings", brand: "Farrow & Ball" }, savedCount: 543 },
  { id: "feed-29", type: "room", title: "Warm Contemporary Entry", description: "Sculptural console, warm plaster walls, and statement pendant", imageUrl: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=800&fit=crop", category: "hallway", style: "contemporary", tags: ["entry", "sculptural", "pendant"], savedCount: 167 },
  { id: "feed-30", type: "room", title: "Moody Library Office", description: "Dark green walls, leather seating, and floor-to-ceiling bookshelves", imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=1000&fit=crop", category: "office", style: "traditional", tags: ["library", "dark green", "leather"], savedCount: 523 },
];

export const PAINT_COLORS: PaintColor[] = [
  // Sherwin-Williams
  { id: "sw-7029", hex: "#D0C8B8", name: "Agreeable Gray", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 60, family: "gray", rgb: { r: 208, g: 200, b: 184 } },
  { id: "sw-7015", hex: "#C8BFA8", name: "Repose Gray", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 58, family: "gray", rgb: { r: 200, g: 191, b: 168 } },
  { id: "sw-7012", hex: "#B5AD9E", name: "Creamy", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 81, family: "white", rgb: { r: 245, g: 236, b: 215 } },
  { id: "sw-6119", hex: "#C5BDAA", name: "Antique White", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 72, family: "white", rgb: { r: 242, g: 232, b: 208 } },
  { id: "sw-7036", hex: "#D5CFC3", name: "Accessible Beige", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 58, family: "beige", rgb: { r: 213, g: 207, b: 195 } },
  { id: "sw-6258", hex: "#3B5E3A", name: "Tricorn Black", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 3, family: "black", rgb: { r: 44, g: 43, b: 42 } },
  { id: "sw-7048", hex: "#54534E", name: "Urbane Bronze", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 8, family: "brown", rgb: { r: 84, g: 83, b: 78 } },
  { id: "sw-6244", hex: "#2E3B32", name: "Pewter Green", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 7, family: "green", rgb: { r: 46, g: 59, b: 50 } },
  { id: "sw-6230", hex: "#576B50", name: "Basil", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 12, family: "green", rgb: { r: 87, g: 107, b: 80 } },
  { id: "sw-7006", hex: "#F1EEE8", name: "Extra White", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 86, family: "white", rgb: { r: 241, g: 238, b: 232 } },
  { id: "sw-6258-2", hex: "#4A6741", name: "Forest Moss", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 11, family: "green", rgb: { r: 74, g: 103, b: 65 } },
  { id: "sw-7005", hex: "#EDEAE4", name: "Pure White", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 84, family: "white", rgb: { r: 237, g: 234, b: 228 } },
  { id: "sw-7008", hex: "#C4BCA8", name: "Alabaster", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 82, family: "white", rgb: { r: 237, g: 234, b: 224 } },
  { id: "sw-6244-b", hex: "#3C4557", name: "Naval", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 4, family: "blue", rgb: { r: 60, g: 69, b: 87 } },
  { id: "sw-9171", hex: "#7B8A82", name: "Evergreen Fog", brand: "sherwin-williams", brandDisplayName: "Sherwin-Williams", lrv: 30, family: "green", rgb: { r: 123, g: 138, b: 130 } },
  // Benjamin Moore
  { id: "bm-oc17", hex: "#F3EEDE", name: "White Dove", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 85, family: "white", rgb: { r: 243, g: 238, b: 222 } },
  { id: "bm-hc154", hex: "#3C4557", name: "Hale Navy", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 5, family: "blue", rgb: { r: 60, g: 69, b: 87 } },
  { id: "bm-oc45", hex: "#F0EDE5", name: "Swiss Coffee", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 82, family: "white", rgb: { r: 240, g: 237, b: 229 } },
  { id: "bm-2163-10", hex: "#464740", name: "Iron Mountain", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 5, family: "gray", rgb: { r: 70, g: 71, b: 64 } },
  { id: "bm-cc-40", hex: "#918A7E", name: "Cloud White", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 87, family: "white", rgb: { r: 244, g: 241, b: 234 } },
  { id: "bm-hc172", hex: "#4B6858", name: "Tarrytown Green", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 10, family: "green", rgb: { r: 75, g: 104, b: 88 } },
  { id: "bm-2111-60", hex: "#C5C2BD", name: "Balboa Mist", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 67, family: "gray", rgb: { r: 197, g: 194, b: 189 } },
  { id: "bm-cc-20", hex: "#F5EDD7", name: "Decorator's White", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 84, family: "white", rgb: { r: 245, g: 237, b: 215 } },
  { id: "bm-af-685", hex: "#304848", name: "Newburyport Blue", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 6, family: "blue", rgb: { r: 48, g: 72, b: 72 } },
  { id: "bm-oc-152", hex: "#EAE2D0", name: "Calming Cream", brand: "benjamin-moore", brandDisplayName: "Benjamin Moore", lrv: 77, family: "beige", rgb: { r: 234, g: 226, b: 208 } },
  // Farrow & Ball
  { id: "fb-2001", hex: "#F4EDE4", name: "School House White", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 81, family: "white", rgb: { r: 244, g: 237, b: 228 } },
  { id: "fb-31", hex: "#2B2B2B", name: "Railings", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 2, family: "black", rgb: { r: 43, g: 43, b: 43 } },
  { id: "fb-47", hex: "#C5B8A5", name: "Joa's White", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 59, family: "beige", rgb: { r: 197, g: 184, b: 165 } },
  { id: "fb-201", hex: "#938578", name: "Shaded White", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 73, family: "white", rgb: { r: 230, g: 222, b: 210 } },
  { id: "fb-229", hex: "#2E3F38", name: "Green Smoke", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 9, family: "green", rgb: { r: 46, g: 63, b: 56 } },
  { id: "fb-30", hex: "#E7DFD4", name: "Hague Blue", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 3, family: "blue", rgb: { r: 42, g: 60, b: 68 } },
  { id: "fb-274", hex: "#F0E8DC", name: "Ammonite", brand: "farrow-ball", brandDisplayName: "Farrow & Ball", lrv: 77, family: "white", rgb: { r: 240, g: 232, b: 220 } },
  // Behr
  { id: "behr-n520", hex: "#D0C8B8", name: "Blank Canvas", brand: "behr", brandDisplayName: "Behr", lrv: 73, family: "white", rgb: { r: 240, g: 231, b: 216 } },
  { id: "behr-ppu18", hex: "#9B948A", name: "Cathedral Gray", brand: "behr", brandDisplayName: "Behr", lrv: 32, family: "gray", rgb: { r: 155, g: 148, b: 138 } },
  { id: "behr-n310", hex: "#C5B9A0", name: "Wheat Bread", brand: "behr", brandDisplayName: "Behr", lrv: 50, family: "beige", rgb: { r: 197, g: 185, b: 160 } },
  { id: "behr-ppu24", hex: "#C8C1B5", name: "Silver Drop", brand: "behr", brandDisplayName: "Behr", lrv: 56, family: "gray", rgb: { r: 200, g: 193, b: 181 } },
  { id: "behr-s430", hex: "#4C6B5A", name: "Pine Brook", brand: "behr", brandDisplayName: "Behr", lrv: 13, family: "green", rgb: { r: 76, g: 107, b: 90 } },
];

export const COLOR_PALETTES: ColorPalette[] = [
  { id: "pal-1", name: "Coastal Breeze", colors: ["#F4EDE4", "#C5D5E4", "#8EACCD", "#4A7C9B", "#2E5266"], style: "coastal", createdAt: "2025-03-15T00:00:00Z" },
  { id: "pal-2", name: "Modern Farmhouse", colors: ["#F1EEE8", "#D5CFC3", "#8B8578", "#54534E", "#2C2C2C"], style: "farmhouse", createdAt: "2025-03-10T00:00:00Z" },
  { id: "pal-3", name: "Forest Retreat", colors: ["#F0E8DC", "#C5BDAA", "#7B8A82", "#4A6741", "#2E3B32"], style: "rustic", createdAt: "2025-03-08T00:00:00Z" },
  { id: "pal-4", name: "Scandinavian Light", colors: ["#FAFAF8", "#F3EEDE", "#E7DFD4", "#C5C2BD", "#918A7E"], style: "scandinavian", createdAt: "2025-02-20T00:00:00Z" },
  { id: "pal-5", name: "Industrial Edge", colors: ["#F5F5F5", "#B0ADA8", "#7A7772", "#464740", "#2B2B2B"], style: "industrial", createdAt: "2025-02-15T00:00:00Z" },
  { id: "pal-6", name: "Art Deco Luxe", colors: ["#F5EDD7", "#C9A96E", "#8B6914", "#3C4557", "#1A1A2E"], style: "art-deco", createdAt: "2025-02-10T00:00:00Z" },
  { id: "pal-7", name: "Desert Sunrise", colors: ["#F9F1E6", "#E8C9A0", "#D4956B", "#A86548", "#5C3524"], style: "bohemian", createdAt: "2025-01-28T00:00:00Z" },
  { id: "pal-8", name: "Moody Blues", colors: ["#E0E5EC", "#8EACCD", "#4A7C9B", "#3C4557", "#1E2A3A"], style: "traditional", createdAt: "2025-01-20T00:00:00Z" },
  { id: "pal-9", name: "Warm Minimalist", colors: ["#F3EEDE", "#EAE2D0", "#D0C8B8", "#C5B9A0", "#918A7E"], style: "minimalist", createdAt: "2025-01-15T00:00:00Z" },
  { id: "pal-10", name: "Mid-Century Modern", colors: ["#F5EDD7", "#D4956B", "#8B6914", "#576B50", "#2C2C2C"], style: "mid-century", createdAt: "2025-01-10T00:00:00Z" },
  { id: "pal-11", name: "Olive & Stone", colors: ["#EDEAE4", "#C5BDAA", "#918A7E", "#576B50", "#3B3B35"], style: "contemporary", createdAt: "2025-01-05T00:00:00Z" },
  { id: "pal-12", name: "Blush & Sage", colors: ["#F5E6E0", "#D4A69A", "#B89B8E", "#7B8A82", "#4A6741"], style: "bohemian", createdAt: "2024-12-20T00:00:00Z" },
];

export const MOCK_MOODBOARDS: Moodboard[] = [
  {
    id: "board-1",
    userId: "usr_client_1",
    title: "Coastal Exterior",
    description: "Beach house exterior inspiration with light blues and natural wood",
    coverImageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    isPublic: false,
    items: [],
    createdAt: "2025-03-20T10:00:00Z",
    updatedAt: "2025-03-25T14:30:00Z",
  },
  {
    id: "board-2",
    userId: "usr_client_1",
    title: "Minimalist Kitchen",
    description: "Clean lines, warm whites, and natural stone countertops",
    coverImageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=600",
    isPublic: true,
    items: [],
    createdAt: "2025-03-18T08:00:00Z",
    updatedAt: "2025-03-22T16:00:00Z",
  },
  {
    id: "board-3",
    userId: "usr_client_1",
    title: "Matte Black Finishes",
    description: "Bold contrast with matte black hardware, trim, and fixtures",
    coverImageUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=600",
    isPublic: false,
    items: [],
    createdAt: "2025-03-15T12:00:00Z",
    updatedAt: "2025-03-20T09:00:00Z",
  },
];

export const ROOM_CATEGORIES = [
  { id: "living-room", label: "Living Room", icon: "Sofa" },
  { id: "kitchen", label: "Kitchen", icon: "CookingPot" },
  { id: "bedroom", label: "Bedroom", icon: "Bed" },
  { id: "bathroom", label: "Bathroom", icon: "Bath" },
  { id: "exterior", label: "Exterior", icon: "Home" },
  { id: "office", label: "Office", icon: "Monitor" },
  { id: "dining-room", label: "Dining Room", icon: "UtensilsCrossed" },
  { id: "hallway", label: "Hallway", icon: "DoorOpen" },
] as const;

export const STYLE_TAGS = [
  { id: "modern", label: "Modern" },
  { id: "traditional", label: "Traditional" },
  { id: "coastal", label: "Coastal" },
  { id: "industrial", label: "Industrial" },
  { id: "scandinavian", label: "Scandinavian" },
  { id: "art-deco", label: "Art Deco" },
  { id: "farmhouse", label: "Farmhouse" },
  { id: "minimalist", label: "Minimalist" },
  { id: "bohemian", label: "Bohemian" },
  { id: "mid-century", label: "Mid-Century" },
  { id: "contemporary", label: "Contemporary" },
  { id: "rustic", label: "Rustic" },
] as const;
